import { ThemeMode } from '@fromcode119/core/client';
import { ViewMode } from '@/app/media/enums/view-mode.enum';
import type { ChangeEvent, DragEvent, RefObject } from 'react';
import type { IMediaFolder } from '@/app/media/interfaces/media-folder.interface';
import type { IMediaItem } from '@/app/media/interfaces/media-item.interface';
import type { IMovingItem } from '@/app/media/interfaces/moving-item.interface';

export interface IMediaPageModel {
  theme: ThemeMode;
  items: IMediaItem[];
  folders: IMediaFolder[];
  currentFolderId: number | null;
  setCurrentFolderId: (id: number | null) => void;
  folderPath: IMediaFolder[];
  loading: boolean;
  uploading: boolean;
  searchQuery: string;
  setSearchQuery: (value: string) => void;
  viewMode: ViewMode;
  setViewMode: (mode: ViewMode) => void;
  error: string | null;
  setError: (value: string | null) => void;
  isDragOver: boolean;
  isFolderPromptOpen: boolean;
  setIsFolderPromptOpen: (value: boolean) => void;
  isRenamePromptOpen: boolean;
  setIsRenamePromptOpen: (value: boolean) => void;
  isDeleteDialogOpen: boolean;
  setIsDeleteDialogOpen: (value: boolean) => void;
  isFolderDeleteDialogOpen: boolean;
  setIsFolderDeleteDialogOpen: (value: boolean) => void;
  isMoveDialogOpen: boolean;
  setIsMoveDialogOpen: (value: boolean) => void;
  setDeletingId: (id: number | null) => void;
  editingFolder: IMediaFolder | null;
  setEditingFolder: (folder: IMediaFolder | null) => void;
  editingItem: IMediaItem | null;
  setEditingItem: (item: IMediaItem | null) => void;
  setMovingItem: (item: IMovingItem | null) => void;
  isActionLoading: boolean;
  optimizingId: number | null;
  fileInputRef: RefObject<HTMLInputElement | null>;
  handleCreateFolder: (name: string) => Promise<void>;
  handleRenameFolder: (name: string) => Promise<void>;
  handleDeleteFolder: () => Promise<void>;
  handleMove: (targetFolderId: number | null) => Promise<void>;
  handleUpload: (e: ChangeEvent<HTMLInputElement>) => Promise<void>;
  handleDragEnter: (e: DragEvent) => void;
  handleDragOver: (e: DragEvent) => void;
  handleDragLeave: (e: DragEvent) => void;
  handleDrop: (e: DragEvent) => Promise<void>;
  handleDelete: () => Promise<void>;
  handleOptimize: (item: IMediaItem) => Promise<void>;
  handleUpdateDetails: (alt: string, caption: string) => Promise<void>;
}
