export interface IRuntimeBridgeInstallArgs {
  apiUrl?: string;
  registerContentTransformer: (...args: any[]) => void;
  registerSlotComponent: (...args: any[]) => void;
  registerFieldComponent: (...args: any[]) => void;
  registerOverride: (...args: any[]) => void;
  registerMenuItem: (...args: any[]) => void;
  replaceMenuItems: (...args: any[]) => void;
  registerCollection: (...args: any[]) => void;
  replaceCollections: (...args: any[]) => void;
  registerPlugins: (...args: any[]) => void;
  registerTheme: (...args: any[]) => void;
  registerSettings: (...args: any[]) => void;
  registerTranslations: (...args: any[]) => void;
  registerPluginApi: (...args: any[]) => void;
  getPluginApi: (...args: any[]) => any;
  hasPluginApi: (...args: any[]) => boolean;
  setPluginState: (...args: any[]) => void;
  stableLoadConfig: (...args: any[]) => Promise<any>;
  stableGetFrontendMetadata: (...args: any[]) => Promise<any>;
  emit: (...args: any[]) => void;
  on: (...args: any[]) => any;
  stableT: (...args: any[]) => any;
  stableApiBridge: Record<string, any>;
  setLocale: (...args: any[]) => void;
  usePlugins: (...args: any[]) => any;
  useTranslation: (...args: any[]) => any;
  usePluginState: (...args: any[]) => any;
  useSystemShortcodes: (...args: any[]) => any;
  CollectionQueryUtils: any;
  BrowserLocalization: any;
  LocalizationUtils: any;
  RelationUtils: any;
  CoercionUtils: any;
  StringUtils: any;
  NumberUtils: any;
  FormatUtils: any;
  ApiVersionUtils: any;
  CollectionUtils: any;
  PaginationUtils: any;
  HookEventUtils: any;
  isReady: boolean;
  PluginsProvider: any;
  RuntimeConstants: any;
  getIcon: (name: string) => any;
  FrameworkIconRegistry: any;
  FrameworkIcons: any;
  IconNames: any;
  createProxyIcon: (...args: any[]) => any;
  RootFramework: any;
  Slot: any;
  Override: any;
  AccountShell: any;
  SlotsContext: any;
  Platform: any;
  AccountShellDefault: any;
  AccountSectionRegistry: any;
  AccountSection: any;
  AccountSectionIcons: any;
  AccountShellSkeleton: any;
  AccountShellPlaceholder: any;
  AccountClass: any;
  /** The AuthMode Enum. A VALUE the theme reads at class-init — must be on the bridge, not lazy. */
  AuthMode: any;
  AuthShell: any;
  RecordsHub: any;
  // reactor's OOP surface, handed to plugin/theme bundles so they never import @fromcode119/reactor
  /** reactor's raw React namespace. Listed in SDK_REACT_EXPORT_KEYS, so it MUST be supplied here too. */
  ReactPrimitives: any;
  Reactor: any;
  PureReactor: any;
  Provider: any;
  Bridge: any;
  Enum: any;
  Context: any;
  prop: any;
  state: any;
  bound: any;
  watch: any;
  ref: any;
  ReactRef: typeof import('react');
  ReactDOMRef: any;
  runtimeModules?: Record<string, any>;
  stabilityRef: import('react').MutableRefObject<any>;
}
