import {
  LayoutDashboard,
  Puzzle,
  Users,
  Settings,
  Image,
  Zap as ZapIcon,
  Package,
  Menu,
  Search,
  Sun,
  Moon,
  Bell,
  User,
  LogOut,
  HelpCircle,
  ChevronDown,
  ChevronUp,
  ChevronRight,
  ArrowLeft,
  X,
  Home,
  Plus,
  Trash2,
  Pencil,
  Save,
  Download,
  Upload,
  RefreshCw,
  ExternalLink,
  MoreHorizontal,
  Filter,
  Calendar,
  UserCheck,
  Eye,
  Globe,
  Palette,
  Smartphone,
  Layers,
  CheckCircle2,
  AlertCircle,
  AlertTriangle,
  Info,
  Loader2,
  File,
  FileText,
  Folder,
  Grid,
  List,
  FolderPlus,
  Box,
  ShoppingBag,
  Database,
  Terminal,
  Activity,
  Clock,
  TrendingUp,
  CheckSquare,
  Code,
  ChartNoAxesColumn,
  Mail,
  Lock,
  ShieldCheck,
  ShieldAlert,
  UserPlus,
  Orbit,
  ArrowRight,
  Puzzle as PuzzleIcon,
  ShoppingCart,
  CreditCard,
  Tag,
  Briefcase,
  History,
  Image as ImageIcon,
  Share2,
  AlertCircle as AlertIcon,
  AlertTriangle as WarningIcon,
  CheckCircle2 as CheckIcon,
  Info as InfoIcon,
  RefreshCw as RefreshIcon,
  Plus as PlusIcon,
  Trash2 as TrashIcon,
  Settings as SettingsIcon,
  Search as SearchIcon,
  LayoutDashboard as DashboardIcon,
  Users as UsersIcon,
  Image as MediaIcon
} from 'lucide-react';

/**
 * Framework Icon Library
 * Individual imports ensure only used icons are bundled into the main app.
 */
export const FrameworkIcons = {
  // Navigation & Actions
  Dashboard: LayoutDashboard,
  DashboardIcon: LayoutDashboard,
  Plugins: Puzzle,
  PluginsIcon: Puzzle,
  Puzzle: Puzzle,
  PuzzleIcon: Puzzle,
  Users: Users,
  UsersIcon: Users,
  Settings: Settings,
  SettingsIcon: Settings,
  Media: Image,
  MediaIcon: Image,
  Image: Image,
  ImageIcon: Image,
  Layout: Layers,
  System: ZapIcon,
  Package: Package,
  Menu: Menu,
  Search: Search,
  SearchIcon: Search,
  Sun: Sun,
  Moon: Moon,
  Bell: Bell,
  User: User,
  Logout: LogOut,
  Help: HelpCircle,
  Down: ChevronDown,
  Up: ChevronUp,
  Right: ChevronRight,
  Left: ArrowLeft,
  Close: X,
  Home: Home,
  Plus: Plus,
  PlusIcon: Plus,
  Trash: Trash2,
  TrashIcon: Trash2,
  Edit: Pencil,
  Save: Save,
  Download: Download,
  Upload: Upload,
  Refresh: RefreshCw,
  RefreshIcon: RefreshCw,
  External: ExternalLink,
  More: MoreHorizontal,
  Filter: Filter,
  Calendar: Calendar,
  UserCheck: UserCheck,
  Eye: Eye,
  Globe: Globe,
  Palette: Palette,
  Smartphone: Smartphone,
  Layers: Layers,
  Share: Share2,
  Share2: Share2,

  // Status & Feedback
  Check: CheckCircle2,
  CheckIcon: CheckCircle2,
  CheckCircle2: CheckCircle2,
  Alert: AlertCircle,
  AlertIcon: AlertCircle,
  AlertCircle: AlertCircle,
  Warning: AlertTriangle,
  WarningIcon: AlertTriangle,
  AlertTriangle: AlertTriangle,
  Info: Info,
  InfoIcon: Info,
  Loader: Loader2,
  
  // Content & Data
  File: File,
  Text: FileText,
  Folder: Folder,
  Grid: Grid,
  List: List,
  FolderPlus: FolderPlus,
  Box: Box,
  ShoppingBag: ShoppingBag,
  ShoppingCart: ShoppingBag,
  Database: Database,
  Terminal: Terminal,
  Activity: Activity,
  Clock: Clock,
  History: History,
  TrendingUp: TrendingUp,
  CheckSquare: CheckSquare,
  Code: Code,
  Chart: ChartNoAxesColumn,
  ChartNoAxesColumn: ChartNoAxesColumn,
  
  // Auth & Security
  Mail: Mail,
  Lock: Lock,
  Shield: ShieldCheck,
  ShieldCheck: ShieldCheck,
  ShieldAlert: ShieldAlert,
  UserPlus: UserPlus,
  
  // Ecommerce & Business
  Tag: Tag,
  Briefcase: Briefcase,
  CreditCard: CreditCard,

  // Miscellaneous
  Orbit: Orbit,
  Zap: ZapIcon,
  ArrowRight: ArrowRight
};

export type IconName = keyof typeof FrameworkIcons;
export const IconNames = Object.keys(FrameworkIcons) as IconName[];
