import { existsSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs';
import path from 'node:path';

/**
 * Generates Next's middleware module (`proxy.ts`) from an authored CLASS (`proxy-route.ts`).
 *
 * Next resolves middleware by EXPORT NAME — a `proxy` function and a `config` object — and neither can
 * be a class. Everywhere else `RouteExportPlugin` supplies those exports through a loader, but Next
 * compiles middleware in a SEPARATE pass that does not apply configured loaders: verified by adding a
 * `proxy`/`middleware` rule to the turbopack config AND widening the webpack test regex, after which
 * `next build` still failed with "must export a `proxy` function".
 *
 * So the glue is produced as a FILE, before the build, instead of during it. The authored source stays
 * `export class` only; `proxy.ts` is build output that happens to live beside the source because that is
 * the path Next demands.
 *
 * **Re-verified empirically** (not inherited from a note): giving the root `proxy.ts` its own loader rule
 * in BOTH the turbopack and webpack configs, and authoring it as `export class AdminProxyRoute`, makes
 * `next build` print `✓ Compiled successfully` — the loader DOES run and the module DOES compile — and
 * then fail with *"The file ./proxy.ts must export a function … as a named `proxy` export"*. Next reads
 * the middleware entry's exports in its OWN analysis pass, upstream of the compiled output, so no loader
 * can satisfy it. `verify()` below therefore exists to keep the generated file honest rather than to
 * remove it.
 */
export class MiddlewareGlueGenerator {
  /** The authored class file, and the module Next loads. */
  private static readonly SOURCE = 'proxy-route.ts';
  private static readonly TARGET = 'proxy.ts';

  /** Static members that map straight onto a same-named Next export. */
  private static readonly EXPORTS = ['proxy', 'config'];

  /**
   * The initialiser text of `static <member> = …`, brace-matched.
   *
   * String-aware on purpose: the matcher is a regex written as a STRING, and a brace inside it would
   * end the scan early on a naive match.
   */
  private static staticInitializer(source: string, member: string): string | null {
    const head = new RegExp(`^\\s{2}static\\s+(?:readonly\\s+)?${member}\\s*=\\s*`, 'm').exec(source);
    if (!head) return null;
    const start = head.index + head[0].length;
    let depth = 0;
    let quote = '';
    for (let i = start; i < source.length; i += 1) {
      const ch = source[i];
      if (quote) {
        if (ch === '\\') i += 1;
        else if (ch === quote) quote = '';
        continue;
      }
      if (ch === "'" || ch === '"' || ch === '`') { quote = ch; continue; }
      if (ch === '{' || ch === '[') depth += 1;
      else if (ch === '}' || ch === ']') {
        depth -= 1;
        if (depth === 0) return source.slice(start, i + 1);
      }
    }
    return null;
  }

  private static className(source: string): string | null {
    return /^export\s+class\s+([A-Za-z_$][\w$]*)/m.exec(source)?.[1] ?? null;
  }

  /**
   * The exact text `proxy.ts` must contain for a given authored source.
   *
   * Separate from `generate()` so `verify()` can compare against it without writing anything — that is
   * what lets the build PROVE the file is generated rather than maintained.
   */
  static render(source: string): string {
    const name = MiddlewareGlueGenerator.className(source);
    if (!name) throw new Error(`[nextor] ${MiddlewareGlueGenerator.SOURCE} declares no exported class`);

    const present = MiddlewareGlueGenerator.EXPORTS.filter((member) => (
      new RegExp(`^\\s{2}static\\s+(?:async\\s+)?(?:readonly\\s+)?${member}\\s*[(=:]`, 'm').test(source)
    ));
    if (!present.length) {
      throw new Error(`[nextor] ${name} declares none of: ${MiddlewareGlueGenerator.EXPORTS.join(', ')}`);
    }

    // The alias form, like every other in-package import — a relative specifier here fails the import
    // guard, and generated output is held to the same house style as source.
    const stem = `@/${MiddlewareGlueGenerator.SOURCE.replace(/\.tsx?$/, '')}`;
    const lines = [
      '// GENERATED by @fromcode119/nextor — do not edit, and do not hand-write exports here.',
      `// Source of truth: ${MiddlewareGlueGenerator.SOURCE} ("export class ${name}").`,
      '// Next resolves middleware by export NAME and compiles it in a pass that ignores build loaders,',
      '// so these bindings are produced as a file before `next build` rather than by a transform.',
      `import { ${name} } from '${stem}';`,
      '',
      // `config` must be INLINED. Next statically parses the middleware matcher at compile time and
      // rejects a reference ("the exported `config` field … needs to be a static object"), so the
      // object literal is lifted out of the class rather than pointed at.
      ...present.map((member) => {
        if (member === 'config') {
          const literal = MiddlewareGlueGenerator.staticInitializer(source, member);
          if (!literal) throw new Error(`[nextor] could not read ${name}.config as a static object literal`);
          return `export const config = ${literal};`;
        }
        return `export const ${member} = ${name}.${member};`;
      }),
      '',
    ].join('\n');
    return lines;
  }

  /**
   * Write `<packageDir>/proxy.ts` from `<packageDir>/proxy-route.ts`.
   * Returns the path written, or null when the package has no authored middleware class.
   */
  static generate(packageDir: string): string | null {
    const sourcePath = path.join(packageDir, MiddlewareGlueGenerator.SOURCE);
    if (!existsSync(sourcePath)) return null;

    const body = MiddlewareGlueGenerator.render(readFileSync(sourcePath, 'utf8'));
    const targetPath = path.join(packageDir, MiddlewareGlueGenerator.TARGET);
    // idempotent: only touch the file when the content actually changes, so watch mode stays quiet
    if (!existsSync(targetPath) || readFileSync(targetPath, 'utf8') !== body) {
      writeFileSync(targetPath, body, 'utf8');
    }
    return targetPath;
  }

  /** Remove the glue. Idempotent; returns true when a file was actually deleted. */
  static clean(packageDir: string): boolean {
    const targetPath = path.join(packageDir, MiddlewareGlueGenerator.TARGET);
    if (!existsSync(targetPath)) return false;
    unlinkSync(targetPath);
    return true;
  }

  /**
   * The glue must NOT be sitting in the tree.
   *
   * It exists only for the duration of a `next build` / `next dev` (see `nextor with-middleware`,
   * which deletes it in a `finally`), so a leftover copy means either an interrupted build or someone
   * hand-writing the non-class exports back in. Both are the thing the house rule forbids, so both fail
   * the build.
   *
   * Returns a complaint, or null when the tree is clean.
   */
  static verify(packageDir: string): string | null {
    const sourcePath = path.join(packageDir, MiddlewareGlueGenerator.SOURCE);
    if (!existsSync(sourcePath)) return null;

    const targetPath = path.join(packageDir, MiddlewareGlueGenerator.TARGET);
    if (!existsSync(targetPath)) return null;

    const actual = readFileSync(targetPath, 'utf8');
    const generatedBanner = actual.startsWith('// GENERATED by @fromcode119/nextor');
    return `${MiddlewareGlueGenerator.TARGET} is present in the tree. It holds the non-class exports Next `
      + `demands and must exist ONLY while a Next command runs — delete it. `
      + (generatedBanner
        ? 'It is leftover build output (an interrupted build?).'
        : `It is NOT generator output: author behaviour in ${MiddlewareGlueGenerator.SOURCE} instead.`);
  }
}
