import { existsSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';

/**
 * Emits the one required `export default` that Vite demands of a config module.
 *
 * Vite loads a config file and reads its DEFAULT export — a hard requirement of the tool, exactly like
 * Next's `GET` / `default` / `generateMetadata`. Rather than let that force a non-class export into
 * authored source, the config is written as a plain class (`ThemeViteConfig`, `PluginUiViteConfig`) and
 * this generator produces the throwaway entry that calls it. The generated file is build output, never
 * committed source — the same contract as the other nextor entry generators.
 */
export class ViteConfigEntryGenerator {
  /** Marks the file as generated so no one edits it and no lint/guard counts it as authored code. */
  private static readonly BANNER = '// GENERATED by @fromcode119/nextor — do not edit. Author the class instead.';

  /**
   * Write `<outFile>` re-exporting `<className>.create()` as the default export.
   *
   * @param outFile    absolute path of the config entry Vite will be pointed at
   * @param modulePath module specifier holding the class, relative to `outFile` (no extension)
   * @param className  the exported class with a static `create()`
   */
  /**
   * Complaint string when any of `entries` is still on disk, or `null` when all are absent.
   *
   * The CALLER supplies the paths. nextor is a standalone package — it knows how to generate and check a
   * Vite config entry, never where a particular project keeps one. (An earlier version of this class
   * hardcoded `packages/sdk/src/vite/…`, which welded the toolchain to this repo's layout.)
   */
  static verify(entries: readonly string[]): string | null {
    const present = entries.filter((entry) => existsSync(entry));
    return present.length
      ? `generated Vite config entr${present.length > 1 ? 'ies' : 'y'} left in the tree: ${present.join(', ')}`
      : null;
  }

  /** Remove the given generated entries. Safe to call when they were never written. */
  static clean(entries: readonly string[]): string[] {
    const removed: string[] = [];
    for (const entry of entries) {
      if (existsSync(entry)) { rmSync(entry, { force: true }); removed.push(entry); }
    }
    return removed;
  }

  static write(outFile: string, modulePath: string, className: string): string {
    const source = [
      ViteConfigEntryGenerator.BANNER,
      `import { ${className} } from '${modulePath}';`,
      '',
      `export default ${className}.create();`,
      '',
    ].join('\n');
    mkdirSync(path.dirname(outFile), { recursive: true });
    writeFileSync(outFile, source, 'utf8');
    return outFile;
  }
}
