import type { AssistantClient, AssistantChatParams, AssistantChatResponse, AiActAuditEntry, AiActAuditSink } from '../types.interfaces';

/**
 * EU AI Act compliance decorator for any {@link AssistantClient}. Applied once at the gateway `create()`
 * seam so EVERY provider (OpenAI/Anthropic/Ollama/Gemini) and EVERY caller gets it uniformly. It covers the
 * obligations that live at the model-invocation layer:
 *   - Art. 12 record-keeping / Art. 26 human oversight: every interaction is persisted (provider, model,
 *     purpose, character sizes, duration, risk tier, timestamp) to a RETAINED, QUERYABLE audit sink the
 *     framework injects at boot (`useSink`) — never containing the raw prompt/response text
 *     (privacy-preserving by default). Until a sink is wired it falls back to a structured `[ai-act]`
 *     console line so nothing is silently lost.
 *   - Art. 50 / 52 transparency: the response is stamped with a machine-readable disclosure + risk tier so a
 *     surface can tell the user the content is AI-generated.
 *   - Risk classification: defaults to 'limited' (AI interacting with a natural person → transparency +
 *     logging); a caller passes `riskTier: 'high'` for an income/employment-adjacent feature to flag it.
 * It NEVER changes the model output — pure cross-cutting compliance, so wrapping is always safe.
 */
export class AiActComplianceWrapper {
  private static sink: AiActAuditSink | null = null;

  /**
   * Framework wires the persisted audit sink here at boot (from the AI extension, which owns a DB handle).
   * Idempotent — a second call replaces the sink. Passing null reverts to the console fallback.
   */
  static useSink(sink: AiActAuditSink | null): void {
    AiActComplianceWrapper.sink = sink;
  }

  static wrap(inner: AssistantClient, provider: string): AssistantClient {
    return {
      async chat(params: AssistantChatParams): Promise<AssistantChatResponse> {
        const riskTier = params?.riskTier || 'limited';
        const purpose = String(params?.purpose || 'unspecified');
        const started = Date.now();
        const promptChars = (params?.messages || []).reduce((n, m) => n + String(m?.content || '').length, 0);
        let ok = true;
        let response: AssistantChatResponse;
        try {
          response = await inner.chat(params);
        } catch (error) {
          ok = false;
          AiActComplianceWrapper.log({ provider, purpose, riskTier, ok, ms: Date.now() - started, promptChars, responseChars: 0, model: '', error: (error as Error)?.message });
          throw error;
        }
        const loggedAt = new Date(started).toISOString();
        AiActComplianceWrapper.log({
          provider, purpose, riskTier, ok, ms: Date.now() - started,
          promptChars, responseChars: String(response?.content || '').length, model: String(response?.model || ''),
        });
        return {
          ...response,
          aiAct: { disclosure: AiActComplianceWrapper.disclosure(riskTier), riskTier, loggedAt },
        };
      },
    };
  }

  private static disclosure(riskTier: 'minimal' | 'limited' | 'high'): string {
    return riskTier === 'high'
      ? 'AI-generated. This output may affect income or eligibility — a human must review it before it is acted on (EU AI Act Art. 14).'
      : 'This content was generated by an AI system (EU AI Act Art. 50 transparency).';
  }

  /**
   * Route the structured, prompt/response-text-free record to the persisted sink when the framework has wired
   * one; otherwise fall back to a console line. Auditing must NEVER break or slow the model call, so every
   * path is wrapped and best-effort.
   */
  private static log(entry: AiActAuditEntry): void {
    const sink = AiActComplianceWrapper.sink;
    if (sink) {
      try { sink(entry); } catch { /* auditing must never break a call */ }
      return;
    }
    try { console.info(`[ai-act] ${JSON.stringify({ at: new Date().toISOString(), ...entry })}`); } catch { /* logging must never break a call */ }
  }
}
