import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import path from 'node:path';
import { PluginAliasMigration } from './plugin-alias-migration';

/**
 * Enforces that every import specifier RESOLVES and is written in the house style.
 *
 * Three rules, all of which were violated silently until this class existed:
 *
 *  1. **It must resolve.** A specifier naming a module that does not exist compiles fine when the
 *     import is type-only (the type becomes `any` at the use site) and only surfaces at runtime, or
 *     never. Twenty-eight of these were sitting in the tree — plugin tests pointing at a doubled
 *     `src/ui/src/` segment, and two theme imports naming a module that never existed.
 *
 *  2. **Every in-package import uses the alias — there is no relative form at all.** `@/` for admin and
 *     frontend, `@theme/` for a theme, `@plugin/` for a plugin, `@ai/` for the ai package. Not `./x`, not
 *     `./interfaces/x`, not `../lib/x`: a module is named by where it LIVES, so the specifier never
 *     changes when the importing file moves, and two files importing the same module always spell it the
 *     same way. (An earlier version of this guard exempted same-directory targets; that exemption was
 *     invented here, never asked for, and it left the two forms mixed across the tree. `plugins/` was a
 *     bigger version of the same hole: it was WALKED but had no alias root, so rule 2 could not fire
 *     there at all and 6887 relative specifiers sat unreported until `@plugin/` existed.)
 *
 *  3. Packages with no path alias are exempt from rule 2 — they have no alias to use, so relative is
 *     correct there by definition. That is appearance (no tsconfig paths at all) and the four
 *     TOOLCHAIN packages (archor, reactor, nextor, typor): those build with raw `tsc`, not through
 *     `typor-build`, so `AliasEmitRewrite` never runs on them and an alias would survive into their
 *     `dist` where Node cannot resolve it. typor additionally cannot use one at all — resolving the
 *     alias is its OWN build output, so it would have to be built to be buildable.
 *
 * Lives in archor because it guards a structural boundary, like the SDK and DB guards beside it.
 */
export class ImportGuard {
  private static readonly SKIP = new Set(['node_modules', 'dist', '.next', 'build', 'coverage', '.git']);

  /** Extensions tried when a specifier carries none. */
  private static readonly EXTENSIONS = [
    '.ts', '.tsx', '.js', '.jsx', '.json', '.css', '.less', '.mjs', '.client.ts', '.client.tsx',
  ];

  private static readonly SPEC =
    /(from\s*|import\s*\(\s*|require\s*\(\s*|vi\.mock\(\s*|jest\.mock\(\s*)(['"])([^'"]+)\2/g;

  /**
   * Marker of a nextor-GENERATED module. Generated entries are exempt from the alias STYLE rule (they
   * still must resolve): a Vite config entry in particular has to use a relative specifier, because Vite
   * loads its config with its own loader before any tsconfig `paths` mapping applies — an aliased import
   * there breaks every plugin-UI and theme build.
   */
  private static readonly GENERATED = 'GENERATED by @fromcode119/nextor';

  /**
   * Each typor-built package's PRIVATE alias for its own `src`, as `package -> prefix`.
   *
   * Unlike the Next apps' `@/`, nothing rewrites these at runtime — `typor-build` resolves them to
   * relative paths before tsc emits (see `AliasEmitRewrite`), so the alias exists only in source, which
   * is exactly where this guard enforces it. `next` uses `@nextjs/` because `@next` is a real npm scope
   * present in node_modules and a `@next/*` path mapping would shadow it.
   */
  private static readonly PACKAGE_ALIASES: ReadonlyArray<readonly [string, string]> = [
    ['ai', '@ai/'], ['core', '@core/'], ['database', '@database/'], ['react', '@react/'],
    ['api', '@api/'], ['auth', '@auth/'], ['cache', '@cache/'], ['marketplace-client', '@marketplace-client/'],
    ['media', '@media/'], ['email', '@email/'], ['scheduler', '@scheduler/'], ['plugins', '@plugins/'],
    ['mcp', '@mcp/'], ['sdk', '@sdk/'], ['next', '@nextjs/'], ['cli', '@cli/'],
  ];

  /** Every alias prefix this guard understands, longest first so `@marketplace-client/` wins over `@m…`. */
  static aliasPrefixes(): string[] {
    return ['@/', '@theme/', PluginAliasMigration.ALIAS, ...ImportGuard.PACKAGE_ALIASES.map(([, prefix]) => prefix)]
      .sort((a, b) => b.length - a.length);
  }

  /**
   * Modules Vite pulls in while LOADING ITS OWN CONFIG — the whole `sdk/src/vite` tree.
   *
   * Vite resolves its config graph with its own loader, BEFORE any tsconfig `paths` mapping applies, so an
   * aliased specifier anywhere in that graph fails to resolve and every theme / plugin-UI build dies with
   * `Cannot find module '@sdk/vite/…'`. They must stay relative, and this guard must not push them back.
   * (`build-plugins.sh` reports a theme failure as a WARNING, not `⚠ Failed`, so grepping for plugin
   * failures alone will not catch it — the theme pack step is the check that does.)
   */
  private static readonly RELATIVE_ONLY = /(^|\/)sdk\/src\/vite\//;

  /** The alias root owning this file, or null for a package that has no alias. */
  private static aliasRoot(file: string, framework: string, repoRoot: string): { root: string; prefix: string } | null {
    const real = path.resolve(file);
    if (ImportGuard.RELATIVE_ONLY.test(real.replace(/\\/g, '/'))) return null;
    for (const pkg of ['admin', 'frontend']) {
      const base = path.resolve(framework, 'packages', pkg);
      if (real.startsWith(base + path.sep)) return { root: base, prefix: '@/' };
    }
    // Anchored on the PACKAGE, not on its `src` — same reasoning as the plugin branch below. A
    // `tests/` file sits outside `src` but still resolves INTO it, and an src-anchored root returned
    // null for it, which both suppressed the style rule there (33 relative `../src/…` imports sat
    // unreported) and made every legitimate `@api/…` from `packages/api/tests` a FALSE `BROKEN` —
    // `resolveSpecifier` bails to null when the importer has no alias root, whether or not the target
    // exists. The alias root stays the package's `src` (that is what the prefix maps to); only the
    // guard's reach widens to the whole package.
    for (const [pkg, prefix] of ImportGuard.PACKAGE_ALIASES) {
      const packageRoot = path.resolve(framework, 'packages', pkg);
      if (!real.startsWith(packageRoot + path.sep)) continue;
      const src = path.join(packageRoot, 'src');
      if (existsSync(src)) return { root: src, prefix };
    }
    const themes = path.resolve(repoRoot, 'themes');
    if (real.startsWith(themes + path.sep)) {
      const slug = real.slice(themes.length + 1).split(path.sep)[0];
      const src = path.resolve(themes, slug, 'src');
      if (real.startsWith(src + path.sep)) return { root: src, prefix: '@theme/' };
    }
    // A plugin is its own repo and spells its own source root `@plugin/`, exactly as a theme uses
    // `@theme/`. This returned null for every plugin file, so `plugins/` was walked for BROKEN
    // specifiers but the style rule could never fire there — 6861 relative imports sat unreported.
    // Files OUTSIDE `src` (a root `index.ts`, a `tests/` helper) still resolve INTO it, so the alias
    // root is the plugin's `src` while the guard's reach is the whole plugin.
    const plugins = path.resolve(repoRoot, 'plugins');
    if (real.startsWith(plugins + path.sep)) {
      const slug = real.slice(plugins.length + 1).split(path.sep)[0];
      const pluginRoot = path.resolve(plugins, slug);
      // Root, not `src`: `settings.ts` / `seed.ts` / `index.ts` live here, and a src-anchored root made
      // the guard blind to every import of them.
      if (existsSync(path.join(pluginRoot, 'src'))) return { root: pluginRoot, prefix: PluginAliasMigration.ALIAS };
    }
    return null;
  }

  /** Absolute path a specifier points at, `'external'` for packages, or null when it does not exist. */
  static resolveSpecifier(spec: string, importer: string, framework: string, repoRoot: string): string | null {
    const dir = path.dirname(importer);
    let base: string;
    if (spec.startsWith('.')) base = path.normalize(path.join(dir, spec));
    else if (ImportGuard.aliasPrefixes().some((prefix) => spec.startsWith(prefix))) {
      const alias = ImportGuard.aliasRoot(importer, framework, repoRoot);
      if (!alias || !spec.startsWith(alias.prefix)) return null;
      base = path.normalize(path.join(alias.root, spec.slice(alias.prefix.length)));
    } else return 'external';

    if (existsSync(base) && statSync(base).isFile()) return path.resolve(base);
    for (const ext of ImportGuard.EXTENSIONS) {
      if (existsSync(base + ext)) return path.resolve(base + ext);
    }
    for (const ext of ['/index.ts', '/index.tsx']) {
      if (existsSync(base + ext)) return path.resolve(base + ext);
    }
    return existsSync(base) ? 'external' : null;
  }

  private static walk(dir: string, out: string[] = []): string[] {
    let entries: string[];
    try { entries = readdirSync(dir); } catch { return out; }
    for (const name of entries) {
      if (ImportGuard.SKIP.has(name)) continue;
      const full = path.join(dir, name);
      if (statSync(full).isDirectory()) ImportGuard.walk(full, out);
      else if (/\.tsx?$/.test(full) && !full.endsWith('.d.ts')) out.push(full);
    }
    return out;
  }

  /**
   * True when the specifier is not an import THIS file makes: a comment line, or code inside a template
   * literal (a scaffold writing `import Banner from './banner'` into a plugin it generates — that path
   * is relative to the generated file, not to the generator).
   */
  private static notAnImport(source: string, at: number): boolean {
    const lineStart = source.lastIndexOf('\n', at) + 1;
    const line = source.slice(lineStart, at).trimStart();
    if (line.startsWith('*') || line.startsWith('//') || line.startsWith('/*')) return true;
    // `expect(src).not.toContain("from './x'")` — the specifier is DATA inside another string literal,
    // not an import this file makes. An odd number of unescaped quotes before it means we are inside one.
    for (const quote of ['"', "'"]) {
      const before = source.slice(lineStart, at);
      if ((before.split(quote).length - 1) % 2 === 1) return true;
    }
    // an odd number of unescaped backticks before this point means we are inside a template literal
    const backticks = (source.slice(0, at).match(/(?<!\\)`/g) || []).length;
    return backticks % 2 === 1;
  }

  /** Every unresolvable specifier and every style deviation, as printable lines. */
  static scan(repoRoot: string, framework: string): { broken: string[]; style: string[] } {
    const areas = [
      path.join(framework, 'packages'),
      path.join(repoRoot, 'plugins'),
      path.join(repoRoot, 'themes'),
      path.join(repoRoot, 'appearance'),
    ].filter((dir) => existsSync(dir));

    const broken: string[] = [];
    const style: string[] = [];
    for (const area of areas) {
      for (const file of ImportGuard.walk(area)) {
        const source = readFileSync(file, 'utf8');
        const generated = source.includes(ImportGuard.GENERATED);
        const alias = generated ? null : ImportGuard.aliasRoot(file, framework, repoRoot);
        const rel = path.relative(repoRoot, file);
        for (const match of source.matchAll(ImportGuard.SPEC)) {
          const spec = match[3];
          const at = match.index ?? 0;
          const resolved = ImportGuard.resolveSpecifier(spec, file, framework, repoRoot);
          if (resolved === null) {
            if (!ImportGuard.notAnImport(source, at)) broken.push(`${rel}: cannot resolve '${spec}'`);
            continue;
          }
          if (!alias || resolved === 'external') continue;
          if (spec.startsWith('.') && resolved.startsWith(alias.root + path.sep)) {
            style.push(`${rel}: '${spec}' should use the ${alias.prefix} alias`);
          }
        }
      }
    }
    return { broken, style };
  }
}
