module.exports = {
  transform: {
    '^.+\\.tsx?$': [require.resolve('ts-jest'), { tsconfig: 'tsconfig.json' }],
  },
  testEnvironment: 'node',
  testMatch: ['**/tests/**/*.test.ts'],
  moduleNameMapper: {
    '^@fromcode119/core$': '<rootDir>/../core/src',
    '^@fromcode119/core/(.*)$': '<rootDir>/../core/src/$1',
    '^@fromcode119/auth$': '<rootDir>/../auth/src',
    '^@fromcode119/auth/(.*)$': '<rootDir>/../auth/src/$1',
    '^@fromcode119/database$': '<rootDir>/../database/src',
    '^@fromcode119/database/(.*)$': '<rootDir>/../database/src/$1',
    '^@fromcode119/media$': '<rootDir>/../media/src',
    '^@fromcode119/media/(.*)$': '<rootDir>/../media/src/$1',
    '^@fromcode119/sdk$': '<rootDir>/../sdk/src',
    '^@fromcode119/sdk/(.*)$': '<rootDir>/../sdk/src/$1',
    '^@fromcode119/cache$': '<rootDir>/../cache/src',
    '^@fromcode119/cache/(.*)$': '<rootDir>/../cache/src/$1',
    '^@fromcode119/email$': '<rootDir>/../email/src',
    '^@fromcode119/email/(.*)$': '<rootDir>/../email/src/$1',
    '^@fromcode119/scheduler$': '<rootDir>/../scheduler/src',
    '^@fromcode119/scheduler/(.*)$': '<rootDir>/../scheduler/src/$1',
    '^@fromcode119/marketplace-client$': '<rootDir>/../marketplace-client/src',
    '^@fromcode119/marketplace-client/(.*)$': '<rootDir>/../marketplace-client/src/$1',
    '^@fromcode119/plugins$': '<rootDir>/../plugins/src',
    '^@fromcode119/plugins/(.*)$': '<rootDir>/../plugins/src/$1',
    '^@/(.*)$': '<rootDir>/src/$1',
  },
};
