import { ExportFormat } from '@/components/collection/list/enums/export-format.enum';
import { NotificationType } from '@/components/enums/notification-type.enum';
import type React from 'react';

export interface ICollectionListPageViewModel {
  router: any;
  settings: any;
  theme: any;
  columnsMenuRef: React.RefObject<HTMLDivElement>;
  collection: any;
  resolvedSlug: string;
  slotSlug: string;
  pageSize: number;
  frontendUrl: string;
  data: any[];
  pluginSettings: Record<string, any>;
  total: number;
  loading: boolean;
  /** Non-empty when the record fetch failed — never render an empty table as "no records". */
  loadError: string;
  search: string;
  setSearch: React.Dispatch<React.SetStateAction<string>>;
  page: number;
  setPage: React.Dispatch<React.SetStateAction<number>>;
  sort: string;
  handleSort: (newSort: string) => void;
  selectedIds: string[];
  setSelectedIds: React.Dispatch<React.SetStateAction<string[]>>;
  statusFilter: string;
  setStatusFilter: React.Dispatch<React.SetStateAction<string>>;
  fieldFilters: Record<string, string>;
  setFieldFilters: React.Dispatch<React.SetStateAction<Record<string, string>>>;
  visibleColumnIds: string[];
  setVisibleColumnIds: React.Dispatch<React.SetStateAction<string[]>>;
  showColumnsMenu: boolean;
  setShowColumnsMenu: React.Dispatch<React.SetStateAction<boolean>>;
  quickEditExpandedId: string | null;
  setQuickEditExpandedId: React.Dispatch<React.SetStateAction<string | null>>;
  quickEditLoadingId: string | null;
  setQuickEditLoadingId: React.Dispatch<React.SetStateAction<string | null>>;
  quickEditSavingId: string | null;
  setQuickEditSavingId: React.Dispatch<React.SetStateAction<string | null>>;
  quickEditData: Record<string, any>;
  setQuickEditData: React.Dispatch<React.SetStateAction<Record<string, any>>>;
  quickEditInitialData: Record<string, any>;
  setQuickEditInitialData: React.Dispatch<React.SetStateAction<Record<string, any>>>;
  quickEditStatus: { type: NotificationType; message: string } | null;
  setQuickEditStatus: React.Dispatch<React.SetStateAction<{ type: NotificationType; message: string } | null>>;
  quickEditFields: any[];
  deleteDialogState: { mode: 'single'; id: string } | { mode: 'bulk'; ids: string[] } | null;
  setDeleteDialogState: React.Dispatch<React.SetStateAction<{ mode: 'single'; id: string } | { mode: 'bulk'; ids: string[] } | null>>;
  deleteLoading: boolean;
  setDeleteLoading: React.Dispatch<React.SetStateAction<boolean>>;
  statusOptions: any[];
  allColumns: any[];
  selectFilterFields: any[];
  columns: any[];
  setLoading: React.Dispatch<React.SetStateAction<boolean>>;
  fetchData: (targetPage?: number) => Promise<void>;
  handleExport: (format: ExportFormat, ids?: string[]) => Promise<void>;
}
