import react from '@vitejs/plugin-react';
import path from 'node:path';
import type { UserConfig } from 'vite';
import { FromcodeThemeOverridesPlugin } from './fromcode-theme-overrides-plugin';
import { ThemeEntryGenerator } from './theme-entry-generator';

/**
 * Shared, framework-owned Vite config for building ANY theme's SERVER (SSR) bundle — the twin of
 * {@link ThemeViteConfig}, driven by the same env (THEME_DIR, THEME_SLUG) so a theme still ships NO build
 * config of its own.
 *
 * WHY: the storefront currently server-renders 25 characters — just the `<title>`. Every pixel, including
 * the LCP image, is painted after hydration, which pins LCP at ~11 s and caps Lighthouse at ~66 (see
 * `STOREFRONT-PERF-BASELINE.md`). Rendering the theme on the server is the only way past that; this
 * config produces the artifact the server needs.
 *
 * Differences from the client config, each load-bearing:
 *  - `ssr: true` + `target: node20` — output runs in Node, not a browser.
 *  - Externals stay BARE specifiers. The client bundle rewrites them to the `window` runtime registry
 *    (`rollup-plugin-external-globals`) because it loads with no import map; on the server there IS no
 *    registry and Node resolves them normally. Bundling copies instead would give the server a SECOND
 *    React/SDK instance and break `Enum` reference identity.
 *  - No `publicDir` — assets are already emitted by the client build; copying them twice would clobber.
 *  - No minify — server code is never shipped over the wire, and readable frames make SSR errors legible.
 *
 * Vite requires the config module to DEFAULT-export its object. That single required export is generated
 * as build glue (nextor's `ViteConfigEntryGenerator`) so the authored source stays a plain class.
 */
export class ThemeSsrViteConfig {
  /**
   * Left for Node to resolve at runtime rather than bundled. Regexes (not exact strings) so deep imports
   * such as `@chakra-ui/react/styled-system` are external too — a deep import that slipped through would
   * bundle a duplicate of a package whose singleton identity matters.
   */
  private static readonly EXTERNAL = [
    /^react($|\/)/,
    /^react-dom($|\/)/,
    /^@fromcode119\//,
    /^@chakra-ui\//,
    /^@emotion\//,
    /^framer-motion$/,
  ];

  static create(): UserConfig {
    const themeDir = process.env.THEME_DIR as string;
    const themeSlug = process.env.THEME_SLUG || 'theme';

    return {
      plugins: [
        react({ jsxRuntime: 'automatic' }),
        FromcodeThemeOverridesPlugin.create({ themeSlug, priority: 11 }),
      ],
      define: { 'process.env.NODE_ENV': JSON.stringify('production') },
      // A theme addresses its own source as `@theme/*`; without this the SSR build dies on the first
      // such import ("Rollup failed to resolve @theme/cms/constants/cms.constants"). Same mapping the
      // client config declares — it is the theme's own alias, not a framework path.
      resolve: { alias: { '@theme': path.join(themeDir, 'src') } },
      // Same legacy-decorator settings as the client build: Vite compiles theme sources with esbuild and
      // does NOT read the theme's tsconfig, so without this a `@prop` in a theme component is a parse
      // error and the whole build dies. `useDefineForClassFields: false` because a defined field would
      // shadow the accessor the decorator installs.
      esbuild: {
        tsconfigRaw: {
          compilerOptions: { experimentalDecorators: true, useDefineForClassFields: false },
        },
      },
      build: {
        ssr: true,
        outDir: path.join(themeDir, 'ui-ssr'),
        emptyOutDir: true,
        target: 'node20',
        minify: false,
        commonjsOptions: { include: [/node_modules/], transformMixedEsModules: true },
        lib: {
          // GENERATED by ThemeEntryGenerator (framework theme policy) — themes ship no entry file.
          entry: ThemeEntryGenerator.resolveEntry(themeDir),
          fileName: () => 'entry.mjs',
          formats: ['es'],
        },
        // `lib.fileName` is IGNORED under `ssr: true` (the entry would land as `index.mjs`, named after
        // `src/theme-entry.generated.jsx`), so the entry name is pinned here instead. Consumers resolve exactly
        // `ui-ssr/entry.mjs`; leaving it to the entry's basename would make the contract depend on what
        // a theme happens to call its source file.
        rollupOptions: {
          external: ThemeSsrViteConfig.EXTERNAL,
          output: { entryFileNames: 'entry.mjs', chunkFileNames: '[name]-[hash].mjs' },
        },
      },
    };
  }
}
