import { ModuleLocation } from '@extension-builder/module-location';
import { Core } from '@extension-builder/core-bridge';
import { execFile } from 'child_process';
import * as path from 'path';
import * as fs from 'fs';
import { createRequire } from 'module';
import { promisify } from 'util';

/**
 * Builds a plugin's UI with the framework-owned Vite pipeline — the "plugins are just components"
 * model, where `import.meta.glob` discovers every component under src/ui and the SDK's entry
 * template registers each by its static markers. No per-plugin entry file, no generator.
 *
 * This is the build-server twin of `build-plugins.sh`'s `build_plugin_ui` components branch, and it
 * deliberately reuses the SAME artefacts rather than restating them: the entry templates and the Vite
 * config class both come out of the installed `@fromcode119/sdk` (shipped via its `files: ["src/vite"]`),
 * and the config's required `export default` is generated by the same nextor CLI the shell script calls.
 * Building a plugin here and building it locally must produce the same bundle.
 */
export class PluginUiViteCompiler {
  private static readonly execFileAsync = promisify(execFile);
  private static readonly runtimeRequire = ModuleLocation.requireFrom();

  /** Static markers the SDK entry registers on. Mirrors the grep in build-plugins.sh. */
  private static readonly COMPONENT_MARKERS =
    /static (slots|fieldName|override|overrides|cmsBlock|contentTransformer|pluginClient|onMount)/;

  /**
   * True when this UI dir uses the components model — i.e. it has no hand-written entry but does
   * contain at least one component carrying a static registration marker.
   */
  hasComponents(uiDir: string): boolean {
    for (const file of this.listSourceFiles(uiDir)) {
      if (PluginUiViteCompiler.COMPONENT_MARKERS.test(fs.readFileSync(file, 'utf8'))) return true;
    }
    return false;
  }

  /**
   * Admin bundle, then (when the plugin ships `*.storefront.*`) the storefront bundle and its SSR twin.
   * The copied entry is build input and is removed however this exits.
   */
  async build(uiDir: string, slug: string, namespace: string, ssrOutDir: string): Promise<void> {
    const viteDir = this.resolveSdkViteDir();
    const stagingDir = this.createStagingDir(slug);
    const entryTarget = path.join(uiDir, Core.PluginPackageLayout.GENERATED_UI_ENTRY);

    try {
      const configFile = await this.stageConfig(viteDir, stagingDir, 'plugin-ui');
      fs.copyFileSync(path.join(viteDir, 'plugin-ui-entry.tsx'), entryTarget);
      await this.runVite(stagingDir, configFile, {
        PLUGIN_UI_DIR: uiDir,
        PLUGIN_NAMESPACE: namespace,
        PLUGIN_SLUG: slug,
        UI_BUNDLE: 'admin',
        UI_OUT: Core.PluginPackageLayout.UI_ENTRY,
      });

      if (!this.hasStorefrontSources(uiDir)) return;

      fs.copyFileSync(path.join(viteDir, 'plugin-ui-entry.storefront.tsx'), entryTarget);
      await this.runVite(stagingDir, configFile, {
        PLUGIN_UI_DIR: uiDir,
        PLUGIN_NAMESPACE: namespace,
        PLUGIN_SLUG: slug,
        UI_BUNDLE: 'frontend',
        UI_OUT: Core.PluginPackageLayout.FRONTEND_ENTRY,
      });

      await this.buildSsrBundle(viteDir, stagingDir, uiDir, slug, namespace, ssrOutDir);
    } finally {
      fs.rmSync(entryTarget, { force: true });
      fs.rmSync(stagingDir, { recursive: true, force: true });
    }
  }

  /**
   * The server twin of the storefront bundle. Additive and non-fatal, exactly as in build-plugins.sh:
   * a plugin whose storefront code is not Node-importable simply has no server bundle and its surfaces
   * render client-side as before, so a failure here must not fail the plugin's build.
   */
  private async buildSsrBundle(
    viteDir: string,
    stagingDir: string,
    uiDir: string,
    slug: string,
    namespace: string,
    ssrOutDir: string,
  ): Promise<void> {
    try {
      const ssrConfig = await this.stageConfig(viteDir, stagingDir, 'plugin-ui-ssr');
      await this.runVite(stagingDir, ssrConfig, {
        PLUGIN_UI_DIR: uiDir,
        PLUGIN_NAMESPACE: namespace,
        PLUGIN_SLUG: slug,
        PLUGIN_SSR_OUT_DIR: ssrOutDir,
      });
    } catch {
      // Intentionally swallowed — see the doc comment above.
    }
  }

  /**
   * Stage the config next to the node_modules that owns `vite`, then generate its entry there.
   *
   * The config `require`s `@vitejs/plugin-react` at load time, and Node resolves that from the CONFIG
   * FILE's own directory upward. Left inside `node_modules/@fromcode119/sdk/src/vite`, that chain never
   * reaches the build server's own `node_modules` and the build dies with "Cannot find module
   * '@vitejs/plugin-react'". Copying the two authored files (the config class + its only local import)
   * into the vite host dir puts them on a chain where every runtime require resolves — the same relation
   * the framework checkout has naturally, where vite sits at the workspace root above packages/sdk.
   *
   * This is build glue, not a fork: the authored copy stays in the SDK and the staging dir is deleted
   * after the build, exactly like the `.plugin-entry.tsx` copied into the plugin.
   */
  private async stageConfig(viteDir: string, stagingDir: string, base: string): Promise<string> {
    for (const file of [`${base}-vite-config.ts`, 'plugin-ui-css-as-text-plugin.ts']) {
      fs.copyFileSync(path.join(viteDir, file), path.join(stagingDir, file));
    }

    const className = base === 'plugin-ui' ? 'PluginUiViteConfig' : 'PluginUiSsrViteConfig';
    const configFile = path.join(stagingDir, `${base}.config.ts`);
    await PluginUiViteCompiler.execFileAsync(
      process.execPath,
      [
        this.resolveNextorCli(),
        'vite-config',
        path.join(stagingDir, `${base}-vite-config`),
        className,
        configFile,
      ],
      { timeout: 60_000 },
    );
    if (!fs.existsSync(configFile)) {
      throw new Error(`Vite config entry was not generated: ${configFile}`);
    }
    return configFile;
  }

  /** Per-slug so the parallel plugin builds the build server runs never collide on one staging dir. */
  private createStagingDir(slug: string): string {
    const stagingDir = path.join(this.resolveViteHostDir(), `.fromcode-vite-build-${slug}`);
    fs.rmSync(stagingDir, { recursive: true, force: true });
    fs.mkdirSync(stagingDir, { recursive: true });
    return stagingDir;
  }

  private async runVite(stagingDir: string, configFile: string, env: Record<string, string>): Promise<void> {
    await PluginUiViteCompiler.execFileAsync(
      process.execPath,
      [this.resolveViteCli(), 'build', '--config', configFile],
      { cwd: path.dirname(stagingDir), timeout: 300_000, env: { ...process.env, ...env } },
    );
  }

  /** The directory whose `node_modules` provides vite — and therefore `@vitejs/plugin-react` too. */
  private resolveViteHostDir(): string {
    return path.dirname(path.dirname(this.resolvePackageRoot('vite')));
  }

  private hasStorefrontSources(uiDir: string): boolean {
    return this.listSourceFiles(uiDir).some((file) => /\.storefront\.(ts|tsx)$/.test(file));
  }

  private listSourceFiles(uiDir: string): string[] {
    const found: string[] = [];
    const walk = (dir: string): void => {
      for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
        if (entry.name === 'node_modules' || entry.name.startsWith('.')) continue;
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) walk(full);
        else if (/\.(ts|tsx)$/.test(entry.name)) found.push(full);
      }
    };
    if (fs.existsSync(uiDir)) walk(uiDir);
    return found;
  }

  /**
   * The SDK ships its Vite sources (`files: ["dist", "src/vite"]`) so this build server and a local
   * build-plugins.sh run share one copy of the config classes and entry templates. `exports` does not
   * expose them, so locate the package root from its resolved main and walk to src/vite.
   */
  private resolveSdkViteDir(): string {
    const viteDir = path.join(this.resolvePackageRoot('@fromcode119/sdk'), 'src', 'vite');
    if (!fs.existsSync(path.join(viteDir, 'plugin-ui-entry.tsx'))) {
      throw new Error(
        `@fromcode119/sdk does not ship src/vite (looked in ${viteDir}). ` +
          'The installed SDK predates `files: ["dist", "src/vite"]` — rebuild the image against a newer framework.',
      );
    }
    return viteDir;
  }

  private resolveNextorCli(): string {
    return path.join(this.resolvePackageRoot('@fromcode119/next-build-codegen'), 'dist', 'next-build-codegen-cli.cjs');
  }

  private resolveViteCli(): string {
    return path.join(this.resolvePackageRoot('vite'), 'bin', 'vite.js');
  }

  /** Walk up from a package's resolved entry to the directory holding its package.json. */
  private resolvePackageRoot(packageName: string): string {
    let dir = path.dirname(PluginUiViteCompiler.runtimeRequire.resolve(packageName));
    while (dir !== path.dirname(dir)) {
      const manifest = path.join(dir, 'package.json');
      if (fs.existsSync(manifest)) {
        const name = JSON.parse(fs.readFileSync(manifest, 'utf8'))?.name;
        if (name === packageName) return dir;
      }
      dir = path.dirname(dir);
    }
    throw new Error(`Could not locate the installed root of "${packageName}"`);
  }
}
