import { execFile } from 'child_process';
import * as path from 'path';
import * as fs from 'fs';
import { createRequire } from 'module';
import { promisify } from 'util';

/**
 * Builds a theme's UI with the framework-owned Vite pipeline — the build-server twin of
 * `build-plugins.sh`'s `build_theme_bundle`, exactly as {@link PluginUiViteCompiler} is the twin of
 * the plugin branch.
 *
 * A theme repo commits NO build output (`/ui/` and `/ui-ssr/` are gitignored; the theme is just
 * `src/` components + `theme.json` + styles + `public/`), so a cloned theme HAS no bundles until this
 * runs. Before this class existed the build server packaged themes without compiling anything — a
 * fresh clone shipped with no `ui/` at all, and even a clone carrying stale artifacts shipped without
 * the `ui-ssr/entry.mjs` server bundle, which is what lets the frontend server-render the theme
 * (ThemeServerRenderer). That gap is how production served pages whose server HTML had no visible
 * content.
 *
 * The config classes come out of the installed `@fromcode119/sdk` (`files: ["dist", "src/vite"]`) and
 * their required `export default` is generated by the same nextor CLI the shell script calls, so a
 * theme built here and a theme built locally produce the same bundles.
 */
export class ThemeBundleCompiler {
  private static readonly execFileAsync = promisify(execFile);

  private static readonly runtimeRequire = createRequire(__filename);

  /** The authored config classes plus every local VALUE import they load at config time. */
  private static readonly STAGED_SOURCES = [
    'theme-vite-config.ts',
    'theme-ssr-vite-config.ts',
    'fromcode-theme-overrides-plugin.ts',
    'theme-entry-generator.ts',
  ];

  /** True when this source dir is a buildable theme (src/ components + theme.json). */
  hasThemeSources(themeDir: string): boolean {
    return fs.existsSync(path.join(themeDir, 'theme.json')) && fs.existsSync(path.join(themeDir, 'src'));
  }

  /**
   * Client bundle (ui/), then the SSR server bundle (ui-ssr/entry.mjs). The client build is fatal —
   * a theme without ui/ cannot render at all. The SSR build is additive and non-fatal, exactly as in
   * build-plugins.sh: a theme whose components are not Node-importable simply renders client-side.
   */
  async build(themeDir: string, slug: string): Promise<void> {
    const viteDir = this.resolveSdkViteDir();
    await this.installThemeDependencies(themeDir);
    const stagingDir = this.createStagingDir(slug);

    try {
      const clientConfig = await this.stageConfig(viteDir, stagingDir, 'theme-vite-config', 'ThemeViteConfig');
      await this.runVite(stagingDir, clientConfig, { THEME_DIR: themeDir, THEME_SLUG: slug });
      await this.buildSsrBundle(viteDir, stagingDir, themeDir, slug);
    } finally {
      // The generated entry is build INPUT written into the theme's src by the config's
      // ThemeEntryGenerator — never leave it in the source tree (mirrors build-plugins.sh).
      fs.rmSync(path.join(themeDir, 'src', 'theme-entry.generated.jsx'), { force: true });
      fs.rmSync(stagingDir, { recursive: true, force: true });
    }
  }

  private async buildSsrBundle(viteDir: string, stagingDir: string, themeDir: string, slug: string): Promise<void> {
    try {
      const ssrConfig = await this.stageConfig(viteDir, stagingDir, 'theme-ssr-vite-config', 'ThemeSsrViteConfig');
      await this.runVite(stagingDir, ssrConfig, { THEME_DIR: themeDir, THEME_SLUG: slug });
      this.pruneSsrOutput(path.join(themeDir, 'ui-ssr'));
    } catch {
      // Intentionally swallowed — see the doc comment above.
    }
  }

  /**
   * ui-ssr/ must contain ONLY the server bundle modules. An SDK whose theme-ssr config predates
   * `publicDir: false` copies the theme's public/ (favicons — and the site's user uploads) into the
   * output; pruning here keeps that out of the distributed archive regardless of the SDK on this host.
   */
  private pruneSsrOutput(ssrDir: string): void {
    if (!fs.existsSync(ssrDir)) return;
    const walk = (dir: string): void => {
      for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) {
          walk(full);
          if (fs.readdirSync(full).length === 0) fs.rmdirSync(full);
        } else if (!entry.name.endsWith('.mjs')) {
          fs.rmSync(full, { force: true });
        }
      }
    };
    walk(ssrDir);
  }

  /**
   * A theme's components import their runtime deps (Chakra, emotion, …) from the theme's OWN
   * node_modules, and a fresh clone has none — mirror of `ensure_build_dependencies` in
   * build-plugins.sh. Skipped when the theme declares no dependencies.
   */
  private async installThemeDependencies(themeDir: string): Promise<void> {
    if (!fs.existsSync(path.join(themeDir, 'package.json'))) return;
    if (fs.existsSync(path.join(themeDir, 'node_modules'))) return;
    const installArgs = fs.existsSync(path.join(themeDir, 'package-lock.json'))
      ? ['ci', '--no-audit', '--no-fund']
      : ['install', '--no-audit', '--no-fund'];
    await ThemeBundleCompiler.execFileAsync('npm', installArgs, { cwd: themeDir, timeout: 600_000 });
  }

  /**
   * Stage the config next to the node_modules that owns `vite`, then generate its `export default`
   * entry there via nextor — same relation and same reasoning as PluginUiViteCompiler.stageConfig:
   * the config `require`s `@vitejs/plugin-react` (and the theme config `autoprefixer` +
   * `rollup-plugin-external-globals`) at load time, and Node resolves those from the CONFIG FILE's own
   * directory upward.
   */
  private async stageConfig(viteDir: string, stagingDir: string, base: string, className: string): Promise<string> {
    for (const file of ThemeBundleCompiler.STAGED_SOURCES) {
      const target = path.join(stagingDir, file);
      if (!fs.existsSync(target)) fs.copyFileSync(path.join(viteDir, file), target);
    }

    const configFile = path.join(stagingDir, `${base.replace(/-vite-config$/, '')}.config.ts`);
    await ThemeBundleCompiler.execFileAsync(
      process.execPath,
      [this.resolveNextorCli(), 'vite-config', path.join(stagingDir, base), className, configFile],
      { timeout: 60_000 },
    );
    if (!fs.existsSync(configFile)) {
      throw new Error(`Vite config entry was not generated: ${configFile}`);
    }
    return configFile;
  }

  /** Per-slug so parallel builds never collide on one staging dir. */
  private createStagingDir(slug: string): string {
    const stagingDir = path.join(this.resolveViteHostDir(), `.fromcode-vite-build-theme-${slug}`);
    fs.rmSync(stagingDir, { recursive: true, force: true });
    fs.mkdirSync(stagingDir, { recursive: true });
    return stagingDir;
  }

  private async runVite(stagingDir: string, configFile: string, env: Record<string, string>): Promise<void> {
    await ThemeBundleCompiler.execFileAsync(
      process.execPath,
      [this.resolveViteCli(), 'build', '--config', configFile],
      { cwd: path.dirname(stagingDir), timeout: 600_000, env: { ...process.env, ...env } },
    );
  }

  /** The directory whose `node_modules` provides vite — and therefore the config's plugin deps too. */
  private resolveViteHostDir(): string {
    return path.dirname(path.dirname(this.resolvePackageRoot('vite')));
  }

  private resolveSdkViteDir(): string {
    const viteDir = path.join(this.resolvePackageRoot('@fromcode119/sdk'), 'src', 'vite');
    if (!fs.existsSync(path.join(viteDir, 'theme-vite-config.ts'))) {
      throw new Error(
        `@fromcode119/sdk does not ship src/vite theme configs (looked in ${viteDir}). ` +
          'The installed SDK predates the framework-owned theme build — rebuild the image against a newer framework.',
      );
    }
    return viteDir;
  }

  private resolveNextorCli(): string {
    return path.join(this.resolvePackageRoot('@fromcode119/next-build-codegen'), 'dist', 'next-build-codegen-cli.cjs');
  }

  private resolveViteCli(): string {
    return path.join(this.resolvePackageRoot('vite'), 'bin', 'vite.js');
  }

  /** Walk up from a package's resolved entry to the directory holding its package.json. */
  private resolvePackageRoot(packageName: string): string {
    let dir = path.dirname(ThemeBundleCompiler.runtimeRequire.resolve(packageName));
    while (dir !== path.dirname(dir)) {
      const manifest = path.join(dir, 'package.json');
      if (fs.existsSync(manifest)) {
        const name = JSON.parse(fs.readFileSync(manifest, 'utf8'))?.name;
        if (name === packageName) return dir;
      }
      dir = path.dirname(dir);
    }
    throw new Error(`Could not locate the installed root of "${packageName}"`);
  }
}
