/**
 * The first line of a GENERATED `ui/style.css`.
 *
 * `style.css` is a reserved, generated, gitignored name, so a hand-written one would be silently
 * overwritten and its loss hidden by git. Every generated sheet carries a marker; anything without
 * one was authored by a person and the build refuses rather than destroying it. Custom plugin CSS
 * belongs in a NAMED file imported by a component, which stays in `src/ui`, tracked and untouched.
 */
export class PluginStyleMarker {
  /** What this builder writes. */
  static readonly CURRENT = '/*! generated by @fromcode119/extension-builder - do not edit */';

  /**
   * What `build-plugins.sh` wrote. Still accepted, and must stay accepted: every `ui/style.css`
   * already on disk carries it, and a builder that recognised only its own marker would treat all
   * of them as hand-written and refuse to build a single plugin.
   */
  static readonly LEGACY = '/*! generated by build-plugins.sh build_plugin_ui_styles - do not edit */';

  /**
   * Compared as a FIXED STRING, never a regex: the marker contains `/*!`, and `*` is a quantifier,
   * so an unanchored regex match never found the very marker the build had just written — a second
   * run then refused its own output.
   */
  static isGenerated(contents: string): boolean {
    return contents.includes(PluginStyleMarker.CURRENT) || contents.includes(PluginStyleMarker.LEGACY);
  }
}
