import type { ISqlValueEncoder } from '@database/interfaces/sql-value-encoder.interface';
import type { SqlColumnType } from '@database/sql/sql-column-type';

/** One column of a declared table: its name, its type's encoding, and what an insert may leave out. */
export class SqlColumn implements ISqlValueEncoder {
  /** The table this column belongs to — set when the table is defined. */
  table!: object;
  notNull = false;
  primary = false;
  isUnique = false;
  hasDefault = false;
  default: unknown = undefined;
  defaultFn: (() => unknown) | undefined = undefined;
  onUpdateFn: (() => unknown) | undefined = undefined;

  constructor(readonly name: string, readonly type: SqlColumnType, readonly withTimezone = false) {}

  mapToDriverValue(value: unknown): unknown {
    return this.type.encode(value, this);
  }

  mapFromDriverValue(value: unknown): unknown {
    return this.type.decode(value, this);
  }

  /** No declared column is generated by the database alone, so every one takes part in an insert. */
  shouldDisableInsert(): boolean {
    return false;
  }
}
