import { NotificationType } from '@/components/enums/notification-type.enum';

export interface ICollectionEditPageViewModel {
  router: any;
  theme: any;
  settings: any;
  collection: any;
  resolvedSlug: string;
  isNew: boolean;
  pluginSettings: Record<string, any>;
  status: { type: NotificationType; message: string } | null;
  setStatus: (value: { type: NotificationType; message: string } | null) => void;
  deleting: boolean;
  showDeleteConfirm: boolean;
  setShowDeleteConfirm: (value: boolean) => void;
  readOnlyOverrideFields: Record<string, true>;
  readOnlyOverrideTarget: { name: string; label: string } | null;
  setReadOnlyOverrideTarget: (value: { name: string; label: string } | null) => void;
  readOnlyOverridePasswordTarget: { name: string; label: string } | null;
  setReadOnlyOverridePasswordTarget: (value: { name: string; label: string } | null) => void;
  readOnlyOverrideVerifying: boolean;
  formData: Record<string, any>;
  setFormData: (value: Record<string, any>) => void;
  handleSubmit: (e?: any, summary?: string) => Promise<any>;
  saving: boolean;
  fieldErrors: Record<string, string[]>;
  resolvedTitleValue: string;
  slugManuallyEdited: boolean;
  slugWarning: string | null;
  activeTab: string;
  setActiveTab: (value: string) => void;
  selectedRevision: any | null;
  setSelectedRevision: (value: any | null) => void;
  activeVersionId: number | null;
  setActiveVersionId: (value: number | null) => void;
  revisions: any[];
  revisionsLoading: boolean;
  hasMoreRevisions: boolean;
  showOnlyChanges: boolean;
  setShowOnlyChanges: (value: boolean) => void;
  restoringPermanently: boolean;
  changeSummary: string;
  setChangeSummary: (value: string) => void;
  currentRevIndex: number;
  loadMoreRevisions: () => void;
  handleHardRestore: (version: number) => Promise<void>;
  getPreviewUrl: () => string;
  sidebarFieldSections: Array<{ title: string; fields: any[] }>;
  standardMainFieldSections: Array<{ key: string; title?: string; fields: any[] }>;
  fullWidthMainFieldSections: Array<{ key: string; title?: string; fields: any[] }>;
  navSections: Array<{ key: string; title: string }>;
  handleInputChange: (name: string, value: any) => void;
  handlePatch: (partial: Record<string, any>) => void;
  handleDelete: () => Promise<void>;
  handleReadOnlyOverrideRequest: (target: { name: string; label: string }) => void;
  openReadOnlyOverridePasswordPrompt: () => void;
  handleReadOnlyOverridePasswordConfirm: (password: string) => Promise<void>;
  hasDisablePermalink: boolean;
  showPreview: boolean;
  showPermalink: boolean;
  isFullWidth: boolean;
  hideFooter: boolean;
  hasSidebarFields: boolean;
  renderSidebar: boolean;
  hasBuiltInSidebarContent: boolean;
  statusOptions: any[];
  currentStatusValue: string;
}
