// GENERATED by @fromcode119/next-build-codegen — do not edit, and do not hand-write exports here.
// Source of truth: proxy-route.ts ("export class AdminProxyRoute").
// Next resolves middleware by export NAME and compiles it in a pass that ignores build loaders,
// so these bindings are produced as a file before `next build` rather than by a transform.
import { AdminProxyRoute } from '@/proxy-route';

export const proxy = AdminProxyRoute.proxy;
export const config = {
    matcher: [
      '/((?!api|_next/static|_next/image|_next/webpack-hmr|icons-registry|internal|favicon.ico|robots.txt|.*\\.(?:js|css|json|png|jpg|jpeg|gif|svg|woff|woff2|ttf|otf|webmanifest)).*)',
    ],
  };
